server:
  port: 8081

spring:
  application:
    name: candidat-service
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: APP_GCD
    password: APP_GCD_PWD
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  jackson:
    time-zone: UTC
  cloud:
    config:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    enabled: false

app:
  geo:
    base-url: http://localhost:8082
